// src/lib/report.js
// Issue #16: pure report-building helpers lifted out of FragmentViewer.jsx.
//
// Exports:
//   - topNpeaksPerDye(peaks, n)    — top-n peaks per dye, sorted by height.
//   - sumHeight(peaks)             — total height across B/G/Y/R channels.
//   - buildReportMarkdown(...)     — pandoc-ready markdown report string.
//
// Pure JS. The markdown output is deliberately printable via the lab's
// canonical xelatex recipe (DejaVu Sans main + DejaVu Sans Mono mono).

export function topNpeaksPerDye(peaks, n = 3) {
  const out = {};
  for (const d of ["B", "G", "Y", "R"]) {
    const arr = (peaks?.[d] || []).slice().sort((a, b) => b[1] - a[1]).slice(0, n);
    out[d] = arr.map(p => ({ size: p[0], height: p[1] }));
  }
  return out;
}

export function sumHeight(peaks) {
  let t = 0;
  for (const d of ["B", "G", "Y", "R"]) {
    for (const p of (peaks?.[d] || [])) t += p[1];
  }
  return t;
}

export function buildReportMarkdown({
  samples, peaksBySample, dyeOffsets, componentSizes,
  constructSize, targetStart, targetEnd, generatedAt,
  expectedSpecies = null, pickedGrna = null,
}) {
  const lines = [];
  const dateStr = (generatedAt || new Date()).toISOString().slice(0, 10);
  lines.push(`# Fragment Viewer report`);
  lines.push("");
  lines.push(`- **Date:** ${dateStr}`);
  lines.push(`- **Samples:** ${samples.length}`);
  lines.push(`- **Construct size:** ${constructSize} bp (target window ${targetStart}–${targetEnd})`);
  lines.push(`- **Dye offsets (bp):** B=${dyeOffsets.B.toFixed(3)} · G=${dyeOffsets.G.toFixed(3)} · Y=${dyeOffsets.Y.toFixed(3)} · R=${dyeOffsets.R.toFixed(3)}`);
  if (pickedGrna) {
    lines.push(`- **Cutting Cas9 (picked):** ${pickedGrna.name} — ${pickedGrna.strand} strand · PAM at position ${pickedGrna.pam_start}–${pickedGrna.pam_start + 2} · cut @ construct ${pickedGrna.cut_construct}`);
  }
  lines.push("");
  if (expectedSpecies && expectedSpecies.length > 0) {
    lines.push(`## Expected species`);
    lines.push("");
    lines.push("| ID | Kind | Name | Size (bp) | Dyes |");
    lines.push("|---|---|---|---:|---|");
    for (const sp of expectedSpecies) {
      lines.push(`| ${sp.id} | ${sp.kind} | ${sp.name} | ${Number(sp.size).toFixed(1)} | ${(sp.dyes || []).join("·") || "—"} |`);
    }
    lines.push("");
  }
  lines.push(`## Sample summary`);
  lines.push("");
  lines.push(`| Sample | Total peaks | ΣHeight | Top B | Top G | Top Y | Top R |`);
  lines.push(`|---|---:|---:|---|---|---|---|`);
  for (const s of samples) {
    const p = peaksBySample[s] || {};
    const nPeaks = ["B", "G", "Y", "R", "O"].reduce((t, d) => t + (p[d]?.length || 0), 0);
    const total = sumHeight(p);
    const top = topNpeaksPerDye(p, 1);
    const fmt = (arr) => (arr.length ? `${arr[0].size.toFixed(2)} (h=${arr[0].height.toFixed(0)})` : "—");
    lines.push(`| ${s} | ${nPeaks} | ${total.toFixed(0)} | ${fmt(top.B)} | ${fmt(top.G)} | ${fmt(top.Y)} | ${fmt(top.R)} |`);
  }
  lines.push("");
  lines.push(`## Construct components (bp)`);
  lines.push("");
  lines.push("| Component | Size |");
  lines.push("|---|---:|");
  for (const k of Object.keys(componentSizes || {})) {
    lines.push(`| ${k} | ${componentSizes[k]} |`);
  }
  lines.push("");
  lines.push(`---`);
  lines.push(``);
  lines.push(`*Generated by Fragment Viewer. Build PDF with:*`);
  lines.push("```bash");
  lines.push(`pandoc report.md -o report.pdf --toc --number-sections \\`);
  lines.push(`  --pdf-engine=xelatex \\`);
  lines.push(`  -V mainfont='DejaVu Sans' -V monofont='DejaVu Sans Mono'`);
  lines.push("```");
  return lines.join("\n");
}
